### ISSUE TITLE
it does not work

### ISSUE THREAD

**Issue by PepeParada** [mikib0/chappie#1]
hello. it stopped working right? Your application is very useful, please if you can repair it? thank you

**Comment by mikib0** [comment]
Hi @PepeParada thanks for reporting! 
You're right —the bot isn't providing responses because we've hit the free trial limit of the API. I will try to use a less costly but also powerful model.

**Comment by mikib0** [comment]
Hi @PepeParada thanks for reporting! 
You're right —the bot isn't providing responses because we've hit the free trial limit of the API. I will try to use a less costly but also powerful model.

**Comment by mikib0** [comment]
Hi, @PepeParada I've changed the model to `text-curie-001` which is also powerful and less costly. This will ensure that we don't hit the trial limit early. It turned out that we've also hit the API rate limit. That said, chappie is now back.

Thanks again, for reporting!
